version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: farmaup-postgres
    restart: always
    environment:
      POSTGRES_USER: farmaup
      POSTGRES_PASSWORD: farmaup123
      POSTGRES_DB: farmaup_clientes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - farmaup-network

volumes:
  postgres_data:
    driver: local

networks:
  farmaup-network:
    driver: bridge
